# Noteworthy differences to Python

Coming from Python, how does the experience translate to Julia? Note, also see https://docs.julialang.org/en/v1/manual/noteworthy-differences for a complete overview. Please keep the manual next https://docs.julialang.org/en/v1/manual to this course and try to use the ? help function in the 

### Difference between single and double quotes
There's a difference between ' and " quotes in Julia, whereas in Python they can both be used for strings. In Julia the single quote is used for characters.

In [26]:
println(typeof('a'))
println(typeof("bb"))
println("""a string with odd " characters '... """)
'tryout'

Char
String
a string with odd " characters '... 


LoadError: syntax: invalid character literal

### Built in Array support
In Python you need numpy to have arrays and their related operations. In Julia its built-in:

In [9]:
# Vector of [1,1,1,1,1]
ones(5)

# Random two dimensional matrix
nine = rand(3,3)

3×3 Array{Float64,2}:
 0.504845   0.559678   0.535685
 0.35689    0.268418   0.256252
 0.0179004  0.0742589  0.270605

Note however that the order of columns and rows is different than what you're used to. Multidimensional arrays in Julia are stored in column-major order:

In [8]:
x = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [9]:
x[:]

4-element Array{Int64,1}:
 1
 3
 2
 4

### Missing support
Whereas in Python you would use the numpy masking function, Julia has a built-in Missing type for this. It corresponds to the `NULL` from SQL or `NA` in R. It propagates through the use of normal math functions.

In [10]:
A = [1, missing]

2-element Array{Union{Missing, Int64},1}:
 1
  missing

In [11]:
A .* 2

2-element Array{Union{Missing, Int64},1}:
 2
  missing

### Usage of `end` statement
In Python the loop is ended by indentation:

```python
for x in collection:
    something()

# end of loop
```

While in Julia, you need to explicitly end the loop. The same goes for `function`s, `while`s, `if`s and `else`s and similar constructs:

In [6]:
function square(number::Int)
    number^2
end

for x ∈ 1:10
    square(x)
end

if 1 > 10
    println("What?!")
else
    @info "This seems a sensible result"
end

┌ Info: This seems a sensible result
└ @ Main In[6]:12


Note that you also don't need the `:` character from Python.

### Indexing
Depending on which language you come from, this can be odd, Julia uses one based indexing, just like Fortran. But unlike C and C-like languages such as Python. However, there are options to override this and have custom indexing, not only 0 based, but also custom loops etc.

In [4]:
a = [1,2,3]
println(a[1])
println(a[end])
println(a[1:3])

a[0]

1
3
[1, 2, 3]


BoundsError: BoundsError: attempt to access 3-element Array{Int64,1} at index [0]

## Excercises
We give a few problems here to try out, in a few minutes we'll provide our answers to them. Note that you could share them using [repl.it](repl.it) and generating a link there. In that way we can help you with your problems.

MethodError: MethodError: no method matching *(::Int64, ::Char)
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  *(::T, !Matched::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:54
  *(::Union{Int16, Int32, Int64, Int8}, !Matched::BigInt) at gmp.jl:535
  ...